package Gui_classes;

import DBM_classes.PdfDatabaseManager;
import Test_classes.PDFWithImages;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.PDPageContentStream.AppendMode;
import org.apache.pdfbox.pdmodel.common.PDRectangle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Monzur Elahi Shamim
 */
public class Compose_RemuBill extends javax.swing.JFrame {

	/**
	 * Creates new form compose
	 */
	final int fontSize = 16;
	final String fontPath = "E:/FONTS/Nikosh.ttf";
	final Font customFont = loadCustomFont(fontPath, fontSize);
	final Font boldCustomFont = loadCustomFont(fontPath, fontSize, Font.BOLD);
	

	public Compose_RemuBill() {
		initComponents();
		modifyValues();
	}

	/**
	 * This method is called from within
	 * the constructor to initialize the
	 * form. WARNING: Do NOT modify this
	 * code. The content of this method
	 * is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        previewBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        remuBillDoc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        billSerialNoLabel = new javax.swing.JLabel();
        billSlNoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        msYear = new javax.swing.JComboBox<>();
        msTerm = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        questionairLbl = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        msYear1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        msYear2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        msYear3 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        msYear4 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        questionairLbl1 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Compose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 1, 18))); // NOI18N

        previewBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previewBtn.setText("Preview");
        previewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewBtnMouseClicked(evt);
            }
        });
        previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        remuBillDoc.setBackground(new java.awt.Color(255, 255, 255));
        remuBillDoc.setPreferredSize(new java.awt.Dimension(930, 1315));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/ExamControl_Pad_Header.png"))); // NOI18N

        billSerialNoLabel.setBackground(new java.awt.Color(255, 255, 255));
        billSerialNoLabel.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        billSerialNoLabel.setText("বিলের ক্রমিক নং");

        jLabel2.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel2.setText("পরীক্ষকের নাম :");

        jLabel3.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel3.setText("পদবি সহকারে ঠিকানা :");

        jLabel4.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel4.setText("যে বিভাগের পরীক্ষা:");

        jLabel5.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel5.setText("সনের পরীক্ষা সমূহের প্রশ্নপত্র প্রণয়ন সমন্বয় সাধন এবং উত্তরপত্র মূল্যায়ন ইত্যাদির জন্য আমার পারিশ্রমিকের দাবীসমূহ নিম্নে সন্নিবেশিত হলো:-");

        jLabel6.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel6.setText("Regular Label:");

        jTextField1.setFont(customFont);

        jTextField2.setFont(customFont);

        jTextField3.setFont(customFont);

        jLabel7.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel7.setText("বর্ষ:");

        jLabel8.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel8.setText("টার্ম:");

        jLabel9.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel9.setText("শিক্ষাবর্ষ:");

        msYear.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        msYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "১", "২", "৩", "৪" }));
        msYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msYearActionPerformed(evt);
            }
        });

        msTerm.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        msTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "১", "২" }));

        jTextField4.setFont(customFont);

        jTextField5.setFont(customFont);

        jLabel10.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel10.setText("পরীক্ষা অনুষ্ঠানের তারিখ:");

        jTextField6.setFont(customFont);

        jLabel11.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel11.setText("ক.");

        jTextField7.setFont(customFont);

        jLabel12.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel12.setText("পর্যন্ত");

        jLabel13.setFont(new java.awt.Font("Siyam Rupali", 1, 11)); // NOI18N
        jLabel13.setText("Bold Label:");

        questionairLbl.setFont(new java.awt.Font("Siyam Rupali", 1, 11)); // NOI18N
        questionairLbl.setText("১. প্রশ্নপত্র প্রণয়ন:");

        jTextField8.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField8.setText("dept");

        jLabel15.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel15.setText("থেকে");

        jLabel16.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel16.setText("খ.");

        jLabel17.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel17.setText("গ.");

        jLabel18.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel18.setText("ঘ.");

        jLabel19.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel19.setText("একটি");

        msYear1.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        msYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "২", "৩", "৪" }));
        msYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msYear1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel20.setText("ঘন্টা:");

        jLabel21.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel21.setText("পরীক্ষার");

        jTextField9.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField9.setText("course name");

        jLabel22.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel22.setText("বিষয়");

        jTextField10.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField10.setText("course code");

        jLabel23.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel23.setText("কোর্স কোড ।");

        jLabel24.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel24.setText("একটি");

        msYear2.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        msYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "২", "৩", "৪" }));
        msYear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msYear2ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel25.setText("ঘন্টা:");

        jTextField11.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField11.setText("dept");

        jLabel26.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel26.setText("পরীক্ষার");

        jTextField12.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField12.setText("course name");

        jLabel27.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel27.setText("বিষয়");

        jTextField13.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField13.setText("course code");

        jLabel28.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel28.setText("কোর্স কোড ।");

        jLabel29.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel29.setText("একটি");

        msYear3.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        msYear3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "২", "৩", "৪" }));
        msYear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msYear3ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel30.setText("ঘন্টা:");

        jTextField14.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField14.setText("dept");

        jLabel31.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel31.setText("পরীক্ষার");

        jTextField15.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField15.setText("course name");

        jLabel32.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel32.setText("বিষয়");

        jTextField16.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField16.setText("course code");

        jLabel33.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel33.setText("কোর্স কোড ।");

        jLabel34.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel34.setText("একটি");

        msYear4.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        msYear4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "২", "৩", "৪" }));
        msYear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msYear4ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel35.setText("ঘন্টা:");

        jTextField17.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField17.setText("dept");

        jLabel36.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel36.setText("পরীক্ষার");

        jTextField18.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField18.setText("course name");

        jLabel37.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel37.setText("বিষয়");

        jTextField19.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField19.setText("course code");

        jLabel38.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel38.setText("কোর্স কোড ।");

        questionairLbl1.setFont(new java.awt.Font("Siyam Rupali", 1, 11)); // NOI18N
        questionairLbl1.setText("2. প্রশ্নপত্র সমন্বয় সাধন:");

        jTextField20.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField20.setText("dept");

        jLabel39.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel39.setText("পরীক্ষার");

        jTextField21.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField21.setText("course name");

        jLabel40.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel40.setText("বিষয়");

        jTextField22.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField22.setText("সংখ্যা");

        jLabel41.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel41.setText("টা প্রশ্নপত্র");

        jTextField23.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jTextField23.setText("সংখ্যা");

        jLabel42.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel42.setText("জন সদস্য করেন ।");

        javax.swing.GroupLayout remuBillDocLayout = new javax.swing.GroupLayout(remuBillDoc);
        remuBillDoc.setLayout(remuBillDocLayout);
        remuBillDocLayout.setHorizontalGroup(
            remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remuBillDocLayout.createSequentialGroup()
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(remuBillDocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(remuBillDocLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(billSerialNoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(billSlNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(295, 295, 295)
                                        .addComponent(jLabel13))
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(questionairLbl)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(msYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28))
                                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel29)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(msYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel30)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel33))
                                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(msYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel37)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel38))
                                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(msYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23))))
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(questionairLbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel42)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(remuBillDocLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1))
                                        .addGroup(remuBillDocLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(msYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(msTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4)))
                                .addGap(34, 34, 34)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remuBillDocLayout.setVerticalGroup(
            remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remuBillDocLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billSerialNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billSlNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(56, 56, 56)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(msYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addComponent(questionairLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(msYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(msYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(msYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(msYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionairLbl1)
                    .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel40)
                        .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42)))))
                .addContainerGap(796, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(remuBillDoc);

        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBtn.setText("Save & Submit");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1296, 794));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private void modifyValues() {
//		String fontPath = "E:/FONTS/Nikosh.ttf";
//		Font customFont = loadCustomFont(fontPath, 18);
//		Font boldCustomFont = loadCustomFont(fontPath, 18, Font.BOLD);
		setCommonFont(remuBillDoc,customFont);
		billSerialNoLabel.setFont(customFont);
		billSlNoTxt.setFont(customFont);
		
		questionairLbl.setFont(boldCustomFont);
//		noticeBody.setFont(loadCustomFont(fontPath, 20));
//		noticeBody.setText("এতদ্বারা");

		//designation.setFont(customFont);
	}

	private static Font loadCustomFont(String fontPath, float fontSize) {
		try {
			return Font.createFont(Font.TRUETYPE_FONT, new File(fontPath)).deriveFont(fontSize);
		} catch (IOException | FontFormatException e) {
			e.printStackTrace();
			return null;
		}
	}

	private static Font loadCustomFont(String fontPath, int fontSize, int fontStyle) {
		try {
			Font baseFont = Font.createFont(Font.TRUETYPE_FONT, new File(fontPath));
			return baseFont.deriveFont(fontStyle, fontSize);
		} catch (IOException | FontFormatException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	public static void setCommonFont(JPanel panel, Font font) {
        Component[] components = panel.getComponents();
        for (Component comp : components) {
            if (comp instanceof JLabel) {
                JLabel label = (JLabel) comp;
                label.setFont(font);
            }else if (comp instanceof JTextField) {
                JTextField textField = (JTextField) comp;
                textField.setFont(font);
            } else if (comp instanceof JPanel) {
                setCommonFont((JPanel) comp, font); // Recursive call for nested panels
            }
        }
    }

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
		// TODO add your handling code here:
		setVisible(false);
		Home_Admin object = new Home_Admin();
		object.setVisible(true);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void previewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewBtnMouseClicked
		//remuBillDoc.print(g);
		//printPanel(remuBillDoc);
		String fileName = createPdf();

		pdf_Preview object = new pdf_Preview(fileName, "admin", this, true);
		object.setVisible(true);


    }//GEN-LAST:event_previewBtnMouseClicked

    private void previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBtnActionPerformed

    }//GEN-LAST:event_previewBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
		String fileName = createPdf();		

		// Create a file chooser
		JFileChooser fileChooser = new JFileChooser();

		// Set the file filter to restrict to specific format (e.g., PDF)
		FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files (*.pdf)", "pdf");
		fileChooser.setFileFilter(filter);

		// Show the save dialog
		int userSelection = fileChooser.showSaveDialog(null);

		if (userSelection == JFileChooser.APPROVE_OPTION) {
			File fileToSave = fileChooser.getSelectedFile();
			// Ensure the file has the correct extension
			String savePath = fileToSave.getAbsolutePath();

			if (!savePath.toLowerCase().endsWith(".pdf")) {
				savePath = savePath + ".pdf";
				fileToSave = new File(savePath);
			}

			try {
				File pdfToSave = new File(fileName);
				PDDocument document = PDDocument.load(pdfToSave);
				document.save(fileToSave);
				document.close();
			} catch (IOException ex) {
				Logger.getLogger(pdf_Preview.class.getName()).log(Level.SEVERE, null, ex);
			}
			System.out.println("Save as file: " + savePath);
			String pdfType = "Notice";

			int docId = PdfDatabaseManager.savePDFToDatabase(savePath, pdfType, "Unread");
			//PdfDatabaseManager.saveDocAsText(docId, str_date, "", "", "", bodyText, "Notice", "Unread");
		} else if (userSelection == JFileChooser.CANCEL_OPTION) {
			System.out.println("Save command canceled by user.");
		}
		JOptionPane.showMessageDialog(null, "Document Successfully Saved & Submitted!", "Success", JOptionPane.INFORMATION_MESSAGE);
		this.setVisible(false);

		Home_Admin object = new Home_Admin();
		object.setVisible(true);
    }//GEN-LAST:event_submitBtnMouseClicked

    private void msYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msYearActionPerformed

    private void msYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msYear1ActionPerformed

    private void msYear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msYear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msYear2ActionPerformed

    private void msYear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msYear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msYear3ActionPerformed

    private void msYear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msYear4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msYear4ActionPerformed

	/**
	 * @param args the command line
	 * arguments
	 */
	public static void main(String args[]) throws IOException, Exception {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Compose_RemuBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Compose_RemuBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Compose_RemuBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Compose_RemuBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
//                if (!UserSession.getInstance().isAuthenticated()) {
//                    JOptionPane.showMessageDialog(null, "You need to login first!");
//                } else {
//                    new Compose_Notice().setVisible(true);
//                }
				new Compose_RemuBill().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billSerialNoLabel;
    private javax.swing.JTextField billSlNoTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> msTerm;
    private javax.swing.JComboBox<String> msYear;
    private javax.swing.JComboBox<String> msYear1;
    private javax.swing.JComboBox<String> msYear2;
    private javax.swing.JComboBox<String> msYear3;
    private javax.swing.JComboBox<String> msYear4;
    private javax.swing.JButton previewBtn;
    private javax.swing.JLabel questionairLbl;
    private javax.swing.JLabel questionairLbl1;
    private javax.swing.JPanel remuBillDoc;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

	private String createPdf() {
		String fileName = "tempNotice.pdf";
		try {
			PDDocument document = new PDDocument();
			PDPage page = new PDPage(PDRectangle.A4);
			document.addPage(page);

			// adding header
			PDFWithImages.addHeader(document, page);

			// add Date
			int yPos = (int) page.getMediaBox().getHeight() - 115;
			int leftMargin = 68;
//			str_date = date.getText();
//			PDFWithImages.addLine(document, page, leftMargin, yPos, "তারিখঃ " + str_date);

			PDFWithImages.addLine(document, page, 270, yPos - 60, 20, "নোটিশ", 'b');

			//Draw Underline 
			PDPageContentStream contentStream = new PDPageContentStream(document, page, AppendMode.APPEND, true, true);
			contentStream.moveTo(270, yPos - 55);   // moves "pencil" to a position
			contentStream.lineTo(325, yPos - 55);     // creates an invisible line to another position
			contentStream.stroke();
			contentStream.close();

			//Body text
			yPos = 620;
//			bodyText = noticeBody.getText();
			//PDFWithImages.addParagraph(document, page, yPos, bodyText);

			yPos -= 70;
			PDFWithImages.addDesignation(document, page, yPos);

			//Save document for preview
			document.save(fileName);
			document.close();
		} catch (IOException ex) {
			Logger.getLogger(Compose_RemuBill.class.getName()).log(Level.SEVERE, null, ex);
		} catch (Exception ex) {
			Logger.getLogger(Compose_RemuBill.class.getName()).log(Level.SEVERE, null, ex);

		}
		return fileName;
	}
	
	public static void printPanel(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(new Printable() {
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                panel.printAll(graphics); // Print the panel

                return Printable.PAGE_EXISTS;
            }
        });

        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }
}
