package Gui_classes;

import Other.UserSession;
import Gui_classes.Registration;
import DBM_classes.databaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Monzur Elahi Shamim
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form login
	 */
	Connection conn = null;
	Statement stmt = null;
	ResultSet rs = null;

	public Login() {
		super("Login");
		initComponents();
		conn = databaseConnection.connection();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                password = new javax.swing.JPasswordField();
                mail = new javax.swing.JTextField();
                login = new javax.swing.JButton();
                cancel = new javax.swing.JButton();
                admin = new javax.swing.JRadioButton();
                teacher = new javax.swing.JRadioButton();
                student = new javax.swing.JRadioButton();
                jLabel3 = new javax.swing.JLabel();
                register = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jPanel1.setBackground(new java.awt.Color(0, 204, 204));
                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 1, 18))); // NOI18N
                jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
                jLabel1.setText("Email");

                jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
                jLabel2.setText("Password");

                password.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                passwordActionPerformed(evt);
                        }
                });

                login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                login.setText("Login");
                login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                login.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginActionPerformed(evt);
                        }
                });

                cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                cancel.setText("Cancel");
                cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                cancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelActionPerformed(evt);
                        }
                });

                admin.setBackground(new java.awt.Color(0, 204, 204));
                buttonGroup1.add(admin);
                admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                admin.setText("Admin");

                teacher.setBackground(new java.awt.Color(0, 204, 204));
                buttonGroup1.add(teacher);
                teacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                teacher.setText("Teacher");

                student.setBackground(new java.awt.Color(0, 204, 204));
                buttonGroup1.add(student);
                student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                student.setText("Student");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel3.setText("Login as");

                register.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                register.setText("Register Now");
                register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                register.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                registerMouseClicked(evt);
                        }
                });

                jLabel5.setText("Don't have account?");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(admin)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(teacher)
                                                                        .addGap(10, 10, 10)
                                                                        .addComponent(student))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(jLabel2)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(jLabel1)
                                                                                        .addGap(37, 37, 37)))
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(mail)
                                                                                .addComponent(password))))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(register)
                                                                .addGap(59, 59, 59))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(admin)
                                        .addComponent(teacher)
                                        .addComponent(student))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(register)
                                        .addComponent(jLabel5))
                                .addGap(59, 59, 59))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                setSize(new java.awt.Dimension(434, 523));
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
	    // TODO add your handling code here:
	    try {

		    stmt = conn.createStatement();
		    String userEmail = mail.getText();
		    String userPass = password.getText();
		    if (admin.isSelected() == true) {
			    String sql = "SELECT * FROM admin WHERE mail='" + userEmail + "' AND password='" + userPass + "'";
			    rs = stmt.executeQuery(sql);

			    if (rs.next()) {
				    String userType = rs.getString("user_type");
				    UserSession.getInstance().setUser(userEmail); // Store user email and type in session
				    

				    if ("admin".equals(userType)) {
					    Home_Admin adminHomePage = new Home_Admin();
					    adminHomePage.setVisible(true);
					    setVisible(false);
				    } else if ("super".equals(userType)) {
					    Home_SU superAdminHomePage = new Home_SU();
					    superAdminHomePage.setVisible(true);
					    setVisible(false);
				    }
				    
			    } else {
				    JOptionPane.showMessageDialog(null, "Password or mail is invalid!");
			    }

		    } else if (teacher.isSelected() == true) {
			    //String sql = "SELECT * FROM teacher WHERE Email='" + userEmail + "' && password='" + userPass + "'";

//                rs = stmt.executeQuery(sql);
//                if (rs.next()) {
//                    UserSession.getInstance().setUser(userEmail);
//                    setVisible(false);
//                    Home_Teacher object = new Home_Teacher();
//                    object.setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(null, "Password or mail is invalid!");
//                }
		    } else if (student.isSelected() == true) {
			    String sql = "SELECT * FROM student WHERE eduEmail='" + userEmail + "' && password='" + userPass + "'";

			    rs = stmt.executeQuery(sql);
			    if (rs.next()) {
				    UserSession.getInstance().setUser(userEmail);
				    setVisible(false);
				    Home_Stu object = new Home_Stu();
				    object.setVisible(true);
			    } else {
				    JOptionPane.showMessageDialog(null, "Password or mail is invalid!");
			    }
		    } else {
			    JOptionPane.showMessageDialog(null, "User type not selected!");
		    }

	    } catch (Exception e) {
		    JOptionPane.showMessageDialog(null, e);
	    }
    }//GEN-LAST:event_loginActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
	    // TODO add your handling code here:
	    System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
	    // TODO add your handling code here:
	    setVisible(false);
	    Registration object = new Registration();
	    object.setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JRadioButton admin;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton cancel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JButton login;
        private javax.swing.JTextField mail;
        private javax.swing.JPasswordField password;
        private javax.swing.JLabel register;
        private javax.swing.JRadioButton student;
        private javax.swing.JRadioButton teacher;
        // End of variables declaration//GEN-END:variables
}
