package Gui_classes.Teacher;

import static DB_classes.DatabaseOperations.retrieveTeacherDataFromDatabase;
import DB_classes.PdfDatabaseManager;
import Gui_classes.Admin.Home_Admin;
import Gui_classes.pdf_Preview;
import static Other.Utility.loadCustomFont;
import static Other.Utility.setCommonFont;
import Other.PDFWithImages;
import Other.Teacher;
import Other.UserSession;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Monzur Elahi Shamim
 */
public class NOCApplication extends javax.swing.JFrame {

	/**
	 * Creates new form compose
	 */
	private Teacher teacher;

	final int fontSize = 14;
	final String fontPath = "E:/Fonts/SolaimanLipi_22-02-2012.ttf";
	final Font customFont = loadCustomFont(fontPath, fontSize);
	final Font boldCustomFont = loadCustomFont(fontPath, fontSize, Font.BOLD);

	public NOCApplication() {
		this.teacher = retrieveTeacherDataFromDatabase(UserSession.getInstance().getUser());
		initComponents();
		modifyValues();
	}

	public NOCApplication(String email) {
		this.teacher = retrieveTeacherDataFromDatabase(email);
		initComponents();
		modifyValues();
	}

	/**
	 * This method is called from within
	 * the constructor to initialize the
	 * form. WARNING: Do NOT modify this
	 * code. The content of this method
	 * is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExamRemuBill = new javax.swing.JPanel();
        previewBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        remuBillDoc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        billSerialNoLabel = new javax.swing.JLabel();
        billSlNoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teacherName = new javax.swing.JTextField();
        institutionName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        examYearCBx = new javax.swing.JComboBox<>();
        examTermCBx = new javax.swing.JComboBox<>();
        session = new javax.swing.JTextField();
        calendarYear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deptSelection = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        inSentence = new javax.swing.JTextField();
        startDate = new javax.swing.JTextField();
        endDate = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExamRemuBill.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Compose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 1, 18))); // NOI18N

        previewBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previewBtn.setText("Preview");
        previewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewBtnMouseClicked(evt);
            }
        });
        previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        remuBillDoc.setBackground(new java.awt.Color(255, 255, 255));
        remuBillDoc.setPreferredSize(new java.awt.Dimension(930, 1400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/NOC header.png"))); // NOI18N

        billSerialNoLabel.setBackground(new java.awt.Color(255, 255, 255));
        billSerialNoLabel.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        billSerialNoLabel.setText("স্মারক নং");

        jLabel2.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel2.setText("পরীক্ষকের নাম :");

        jLabel3.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel3.setText("পদবি সহকারে ঠিকানা :");

        jLabel4.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel4.setText("যে বিভাগের পরীক্ষা:");

        jLabel5.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel5.setText("সনের পরীক্ষা সমূহের প্রশ্নপত্র প্রণয়ন সমন্বয় সাধন এবং উত্তরপত্র মূল্যায়ন ইত্যাদির জন্য আমার পারিশ্রমিকের দাবীসমূহ নিম্নে সন্নিবেশিত হলো:-");

        teacherName.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        teacherName.setText("সাব্বির");

        institutionName.setFont(customFont);
        institutionName.setText("নোয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়");

        jLabel7.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel7.setText("বর্ষ:");

        jLabel8.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel8.setText("টার্ম:");

        jLabel9.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel9.setText("শিক্ষাবর্ষ:");

        examYearCBx.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        examYearCBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "১", "২", "৩", "৪" }));
        examYearCBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examYearCBxActionPerformed(evt);
            }
        });

        examTermCBx.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        examTermCBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "১", "২" }));
        examTermCBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examTermCBxActionPerformed(evt);
            }
        });

        session.setFont(customFont);

        calendarYear.setFont(customFont);
        calendarYear.setText("২০২৩");
        calendarYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calendarYearKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel10.setText("পরীক্ষা অনুষ্ঠানের তারিখ:");

        jLabel12.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel12.setText("পর্যন্ত");

        jLabel15.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jLabel15.setText("থেকে");

        deptSelection.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        deptSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "ACCE", "Agriculture", "Applied Mathematics", "Bangla", "BGE", "BMB", "BMS", "Chemistry", "CSTE", "DBA", "EEE", "Economics", "Education", "Educational Administration", "English", "ESDM", "FTNS", "FIMS", "ICE", "LAW", "Microbiology", "MIS", "Oceanography", "Pharmacy", "Physics", "Social Work", "Sociology", "Soil, Water and Environment", "Statistics", "THM", "Zoology" }));
        deptSelection.setSelectedIndex(19);
        deptSelection.setToolTipText("");
        deptSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptSelectionActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jLabel13.setText("কথায়:");

        inSentence.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N

        javax.swing.GroupLayout remuBillDocLayout = new javax.swing.GroupLayout(remuBillDoc);
        remuBillDoc.setLayout(remuBillDocLayout);
        remuBillDocLayout.setHorizontalGroup(
            remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remuBillDocLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remuBillDocLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addGroup(remuBillDocLayout.createSequentialGroup()
                        .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                .addComponent(billSerialNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(billSlNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                .addComponent(calendarYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(remuBillDocLayout.createSequentialGroup()
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(70, 70, 70)
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(examYearCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(remuBillDocLayout.createSequentialGroup()
                                        .addComponent(examTermCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(deptSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remuBillDocLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
            .addGroup(remuBillDocLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(institutionName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        remuBillDocLayout.setVerticalGroup(
            remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remuBillDocLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(institutionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billSerialNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billSlNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(deptSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(examYearCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examTermCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(1044, 1044, 1044)
                .addGroup(remuBillDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inSentence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(remuBillDoc);

        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBtn.setText("Save & Submit");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ExamRemuBillLayout = new javax.swing.GroupLayout(ExamRemuBill);
        ExamRemuBill.setLayout(ExamRemuBillLayout);
        ExamRemuBillLayout.setHorizontalGroup(
            ExamRemuBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamRemuBillLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ExamRemuBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previewBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ExamRemuBillLayout.setVerticalGroup(
            ExamRemuBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamRemuBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ExamRemuBillLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExamRemuBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ExamRemuBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1296, 794));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private void modifyValues() {
		// Setting Teacher Information
//		teacherName.setText(teacher.getNameBn());
//		institutionName.setText(teacher.getDesignation() + ", Dept. of " + teacher.getDept() + ", NSTU");
		// Setting custom font for all jLabel and jTextField
		setCommonFont(remuBillDoc, customFont);

		// Setting custom Bold Font 
//		createPlaceholderText(vivaCrsNmTB,"Enter Course Name");
		//testPanel.setVisible(false);
	}


    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
		// TODO add your handling code here:
		setVisible(false);
		Home_Teacher object = new Home_Teacher();
		object.setVisible(true);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void previewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewBtnMouseClicked
		String fileName = createPdf();
		pdf_Preview object = new pdf_Preview(fileName, "teacher", this, true);
		object.setVisible(true);
    }//GEN-LAST:event_previewBtnMouseClicked

    private void previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBtnActionPerformed

    }//GEN-LAST:event_previewBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
		String fileName = createPdf();

		// Create a file chooser
		JFileChooser fileChooser = new JFileChooser();

		// Set the file filter to restrict to specific format (e.g., PDF)
		FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files (*.pdf)", "pdf");
		fileChooser.setFileFilter(filter);

		// Show the save dialog
		int userSelection = fileChooser.showSaveDialog(null);

		if (userSelection == JFileChooser.APPROVE_OPTION) {
			File fileToSave = fileChooser.getSelectedFile();
			// Ensure the file has the correct extension
			String savePath = fileToSave.getAbsolutePath();

			if (!savePath.toLowerCase().endsWith(".pdf")) {
				savePath = savePath + ".pdf";
				fileToSave = new File(savePath);
			}

			try {
				File pdfToSave = new File(fileName);
				PDDocument document = PDDocument.load(pdfToSave);
				document.save(fileToSave);
				document.close();
			} catch (IOException ex) {
				Logger.getLogger(pdf_Preview.class.getName()).log(Level.SEVERE, null, ex);
			}
			System.out.println("Save as file: " + savePath);
			String pdfType = "Notice";

			int docId = PdfDatabaseManager.savePDFToDatabase(savePath, pdfType, "Unread");
			//PdfDatabaseManager.saveDocAsText(docId, str_date, "", "", "", bodyText, "Notice", "Unread");
		} else if (userSelection == JFileChooser.CANCEL_OPTION) {
			System.out.println("Save command canceled by user.");
		}
		JOptionPane.showMessageDialog(null, "Document Successfully Saved & Submitted!", "Success", JOptionPane.INFORMATION_MESSAGE);
		this.setVisible(false);

		Home_Admin object = new Home_Admin();
		object.setVisible(true);
    }//GEN-LAST:event_submitBtnMouseClicked

    private void deptSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptSelectionActionPerformed
		// TODO add your handling code here:
		JComboBox<String> source = (JComboBox<String>) evt.getSource();

    }//GEN-LAST:event_deptSelectionActionPerformed

    private void examYearCBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examYearCBxActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_examYearCBxActionPerformed

    private void examTermCBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examTermCBxActionPerformed
		// Setting term 

    }//GEN-LAST:event_examTermCBxActionPerformed

    private void calendarYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarYearKeyReleased
		// TODO add your handling code here:

    }//GEN-LAST:event_calendarYearKeyReleased

	/**
	 * @param args the command line
	 * arguments
	 */
	public static void main(String args[]) throws IOException, Exception {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NOCApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NOCApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NOCApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NOCApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
//                if (!UserSession.getInstance().isAuthenticated()) {
//                    JOptionPane.showMessageDialog(null, "You need to login first!");
//                } else {
//                    new Compose_Notice().setVisible(true);
//                }
				new NOCApplication("sabbirejaz.ice@nstu.edu.bd").setVisible(true);
			}
		});
	}

	private String createPdf() {
		String fileName = "E:/PaperlessOffice/PDFs/NOC Sample Format.pdf";
		int BnFontSize = 9;
		int EnFontSize = 9;
		int tableTop, tabelLeft, tableBottom, tableRight;
		try {
			File file = new File("E:/PaperlessOffice/PDFs/NOC Sample Format.pdf");

			// Load the PDF document
			PDDocument document = PDDocument.load(file);

			PDPage page = document.getPage(0);
			document.addPage(page);

			int pageHeight = (int) page.getMediaBox().getHeight();
			int pageWidth = (int) page.getMediaBox().getWidth();
			// adding header
			PDFWithImages.addRemuHeader(document, page);

			// add Date
			int yPos = pageHeight - 80;
			int leftMargin = 30;
			int rightMargin = pageWidth - leftMargin - 20;
			int lineOffSet = 15;
			int subListIndent = 10;

			//Save document for preview
			document.save(fileName);
			document.close();
		} catch (IOException ex) {
			Logger.getLogger(NOCApplication.class.getName()).log(Level.SEVERE, null, ex);
		} catch (Exception ex) {
			Logger.getLogger(NOCApplication.class.getName()).log(Level.SEVERE, null, ex);

		}
		return fileName;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExamRemuBill;
    private javax.swing.JLabel billSerialNoLabel;
    private javax.swing.JTextField billSlNoTxt;
    private javax.swing.JTextField calendarYear;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> deptSelection;
    private javax.swing.JTextField endDate;
    private javax.swing.JComboBox<String> examTermCBx;
    private javax.swing.JComboBox<String> examYearCBx;
    private javax.swing.JTextField inSentence;
    private javax.swing.JTextField institutionName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton previewBtn;
    private javax.swing.JPanel remuBillDoc;
    private javax.swing.JTextField session;
    private javax.swing.JTextField startDate;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField teacherName;
    // End of variables declaration//GEN-END:variables

}
