package Gui_classes.SuperAdmin;

import DB_classes.PdfDatabaseManager;
import DB_classes.databaseConnection;
import Gui_classes.Admin.Home_Admin;
import Gui_classes.pdf_Preview;
import Other.PDFWithImages;
import Other.Utility;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Monzur Elahi Shamim
 */
public class Preview_Office_Order extends javax.swing.JFrame {

	/**
	 * Creates new form compose
	 */
	int docId;
	String userType = "super";

	public Preview_Office_Order() {
		docId = 4;
		initComponents();
		modifyValues();
	}

	public Preview_Office_Order(int docId) {
		this.docId = docId;
		initComponents();
		modifyValues();
	}
	
	public Preview_Office_Order(int docId, String userType) {
		this.docId = docId;
		this.userType = userType;
		initComponents();
		modifyValues();
	}

	/**
	 * This method is called from within
	 * the constructor to initialize the
	 * form. WARNING: Do NOT modify this
	 * code. The content of this method
	 * is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        previewBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        noticeBody = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        designation = new javax.swing.JTextArea();
        approveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Compose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 1, 18))); // NOI18N

        previewBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previewBtn.setText("PDF Preview");
        previewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewBtnMouseClicked(evt);
            }
        });
        previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(930, 1315));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/template_header Bn.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        jLabel2.setText("তারিখঃ");

        date.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        date.setText("৩১/১২/২০২৪ ইং");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Office order title.png"))); // NOI18N

        noticeBody.setColumns(20);
        noticeBody.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        noticeBody.setLineWrap(true);
        noticeBody.setRows(5);
        noticeBody.setWrapStyleWord(true);
        jScrollPane2.setViewportView(noticeBody);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Vrinda", 0, 13)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        designation.setColumns(20);
        designation.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        designation.setRows(5);
        designation.setText("প্রফেসর ড. মোঃ আশিকুর রহমান খান\nচেয়ারম্যান\nতথ্য ও যোগাযোগ প্রকৌশল বিভাগ\nনোয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়");
        jScrollPane4.setViewportView(designation);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel3)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        approveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approveBtnMouseClicked(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(approveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previewBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(previewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(462, 462, 462)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1296, 794));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private void modifyValues() {
		String fontPath = Utility.SOLAIMANLIPI_FONT_PATH;
		Font customFont = loadCustomFont(fontPath, 18);
		Font boldCustomFont = loadCustomFont(fontPath, 18, Font.BOLD);

		String[] rowData = PdfDatabaseManager.retrieveDocAsText(docId);
		if (rowData != null) {
			// Access the retrieved data
			String dateText = rowData[0];
			String bodyText = rowData[4];

			jLabel2.setFont(customFont);
			jLabel2.setText("তারিখঃ");

			date.setFont(customFont);
			date.setText(dateText);
			date.setEditable(false);

			noticeBody.setFont(loadCustomFont(fontPath, 20));
			noticeBody.setText(bodyText);
			noticeBody.setEditable(false);
			

			designation.setFont(loadCustomFont(fontPath, 20));
		}
	}

	private static Font loadCustomFont(String fontPath, float fontSize) {
		try {
			return Font.createFont(Font.TRUETYPE_FONT, new File(fontPath)).deriveFont(fontSize);
		} catch (IOException | FontFormatException e) {
			e.printStackTrace();
			return null;
		}
	}

	private static Font loadCustomFont(String fontPath, int fontSize, int fontStyle) {
		try {
			Font baseFont = Font.createFont(Font.TRUETYPE_FONT, new File(fontPath));
			return baseFont.deriveFont(fontStyle, fontSize);
		} catch (IOException | FontFormatException e) {
			e.printStackTrace();
			return null;
		}
	}

	private String createPdf() {
		String fileName = "NewOfficeOrder.pdf";
		try {
			PDDocument document = new PDDocument();
			PDPage page = new PDPage(PDRectangle.A4);
			document.addPage(page);

			// adding header
			PDFWithImages.addHeader(document, page);

			// add Date
			int yPos = (int) page.getMediaBox().getHeight() - 115;
			int leftMargin = 68;
			String str_date = date.getText();
			PDFWithImages.addLine(document, page, leftMargin, yPos, "তারিখঃ " + str_date);

			PDFWithImages.addLine(document, page, 245, yPos - 60, 20, "অফিস আদেশ", 'b');

			//Draw Underline 
			PDPageContentStream contentStream = new PDPageContentStream(document, page, PDPageContentStream.AppendMode.APPEND, true, true);
			contentStream.moveTo(250, yPos - 55); // moves "pencil" to a position
			contentStream.lineTo(345, yPos - 55);     // creates an invisible line to another position
			contentStream.stroke();
			contentStream.close();

			//Body text
			yPos = 640;
			String bodyText = noticeBody.getText();
			PDFWithImages.addParagraph(document, page, yPos, bodyText);

			//Designation
			yPos -= 60;
			PDFWithImages.addDesignation(document, page, yPos);

			document.save(fileName);
			document.close();
		} catch (IOException ex) {
			Logger.getLogger(Preview_Office_Order.class.getName()).log(Level.SEVERE, null, ex);
		} catch (Exception ex) {
			Logger.getLogger(Preview_Office_Order.class.getName()).log(Level.SEVERE, null, ex);
		}
		return fileName;
	}

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
		// TODO add your handling code here:
		if (backBtn.getText() == "Back") {
			setVisible(false);
			Home_Admin object = new Home_Admin();
			object.setVisible(true);
		} else {
			noticeBody.setEditable(false);
			date.setEditable(false);
			editBtn.setVisible(true);
			approveBtn.setText("Appove");
			backBtn.setText("Back");
			modifyValues();
		}
    }//GEN-LAST:event_backBtnMouseClicked

    private void previewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewBtnMouseClicked
		String fileName = createPdf();
		pdf_Preview object = new pdf_Preview(fileName, "super", this, true);
		object.setVisible(true);
    }//GEN-LAST:event_previewBtnMouseClicked

    private void previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBtnActionPerformed

    }//GEN-LAST:event_previewBtnActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void approveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveBtnMouseClicked
		// TODO add your handling code here:
		String str_date = date.getText();
		String receipient = "";
		String dept = "";
		String subject = "";
		String bodyText = noticeBody.getText();
		if (approveBtn.getText() == "Approve") {
			try (Connection connection = databaseConnection.connection()) {
				String insertQuery = "UPDATE doc_as_text SET status = ? WHERE doc_id = ?";
				PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);

				// Set values for the prepared statement
				preparedStatement.setString(1, "Approved");
				preparedStatement.setInt(2, docId);

				// Execute the query
				preparedStatement.executeUpdate();

				String sql = "UPDATE pdf_storage SET status = ? WHERE pdf_id = ?";
				preparedStatement = connection.prepareStatement(sql);
				// Set values for the prepared statement
				preparedStatement.setString(1, "Approved");
				preparedStatement.setInt(2, docId);

				// Execute the query
				preparedStatement.executeUpdate();

			} catch (SQLException ex) {
				Logger.getLogger(PdfDatabaseManager.class.getName()).log(Level.SEVERE, null, ex);
			}
			JOptionPane.showMessageDialog(null, "Document Successfully Forwarded for Processing!", "Success", JOptionPane.INFORMATION_MESSAGE);
			setVisible(false);
			Home_SU object = new Home_SU();
			object.setVisible(true);
		} else if (approveBtn.getText() == "Update") {
			// Updating pdf content
			String fileName = createPdf();

			// Updating document data and pdf in database
			try (Connection connection = databaseConnection.connection()) {
				//Updating in doc_as_text table
				String insertQuery = "UPDATE doc_as_text "
					+ "SET date = ?, receipient = ?, dept = ?, subject = ?, body = ?, status = ? "
					+ "WHERE doc_id = ?";

				PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);

				// Set values for the prepared statement
				preparedStatement.setString(1, str_date);
				preparedStatement.setString(2, receipient);
				preparedStatement.setString(3, dept);
				preparedStatement.setString(4, subject);
				preparedStatement.setString(5, bodyText);
				preparedStatement.setString(6, "Approved");
				preparedStatement.setInt(7, docId);
				// Execute the query
				preparedStatement.executeUpdate();
				System.out.println("Document id: " + docId + ", is updated in doc as text table.");

				// Updating in pdf_storage table
				String sql = "UPDATE pdf_storage "
					+ "SET byte_pdf = ?, status = ? "
					+ "WHERE pdf_id = ?";
				File pdfFile = new File(fileName);
				try (FileInputStream fis = new FileInputStream(pdfFile)) {
					preparedStatement = connection.prepareStatement(sql);

					// Set values for the prepared statement
					preparedStatement.setBinaryStream(1, fis, (int) pdfFile.length());
					preparedStatement.setString(2, "Approved");
					preparedStatement.setInt(3, docId);

					// Execute the query
					preparedStatement.executeUpdate();
					System.out.println("Document id: " + docId + ", is updated in pdf storage table.");
				} catch (FileNotFoundException ex) {
					Logger.getLogger(Preview_Notice.class.getName()).log(Level.SEVERE, null, ex);
				} catch (IOException ex) {
					Logger.getLogger(Preview_Notice.class.getName()).log(Level.SEVERE, null, ex);
				}

			} catch (SQLException ex) {
				Logger.getLogger(Preview_Notice.class.getName()).log(Level.SEVERE, null, ex);
			}

			pdf_Preview object = new pdf_Preview(fileName, "super", this, true);
			object.setVisible(true);
			//setVisible(false);

		}
    }//GEN-LAST:event_approveBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
		// TODO add your handling code here:
		noticeBody.setEditable(true);
		date.setEditable(true);
		editBtn.setVisible(false);
		approveBtn.setText("Update");
		backBtn.setText("Cancel");
    }//GEN-LAST:event_editBtnMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

	/**
	 * @param args the command line
	 * arguments
	 */
	public static void main(String args[]) throws IOException, Exception {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Preview_Office_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Preview_Office_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Preview_Office_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Preview_Office_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
//                if (!UserSession.getInstance().isAuthenticated()) {
//                    JOptionPane.showMessageDialog(null, "You need to login first!");
//                } else {
//                    new Compose_Office_Order().setVisible(true);
//                }
				new Preview_Office_Order().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField date;
    private javax.swing.JTextArea designation;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea noticeBody;
    private javax.swing.JButton previewBtn;
    // End of variables declaration//GEN-END:variables
}
